canteen/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

#password reset
    re_path(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    re_path(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',auth_views.password_reset_confirm, name='password_reset_confirm'),
    re_path(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),


    path('',include('shop.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path,re_path
from . import views
from django.contrib.auth.views import  (login,logout,password_reset,password_reset_done,password_reset_confirm,)
from django.contrib.auth import views as auth_views
#from .feeds import LatestProductFeed

app_name = 'shop'
urlpatterns = [
    path('',views.index,name='index'),
    path('signup/',views.signup,name='signup'),
    path('login/',views.user_login,  name='login'),
    path('logout/',auth_views.logout,name='logout'),
    #path('feed/',LatestProductFeed(),name='product_feed'),
    re_path(r'^password-change/$', views.change_password, name='change_password'),

    re_path('profile/edit/', views.edit, name='edit'),
    path('', views.dashboard, name='dashboard'),

#products
    re_path(r'^product_list/$', views.product_list, name='product_list'),
    re_path(r'^(?P<category_slug>[-\w]+)/$',views.product_list,name='product_list_by_category'),
    re_path(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',views.product_detail,name='product_detail'),
    path('all/products/',views.allproducts,name='allproducts'),

]

shop/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse

# Create your models here.
class Profile(models.Model):
    CLG_CHOICES = (
        ('MIT', 'Mahakal Institute Of Technology'),
        ('MITM', 'Mahakal Institute Of Technology And Management'),
    )
    BRANCH_CHOICES = (
        ('CS', 'Computer Science And Engineering'),
        ('IT', 'Information Technology'),
        ('CE', 'Civil Engineering'),
        ('ME', 'Mechanical Engineering'),
        ('EC', 'Electronic Engineering'),
    )
    college = models.CharField(max_length=5,choices=CLG_CHOICES)
    branch = models.CharField(max_length=5,choices=BRANCH_CHOICES)
    birth_date = models.DateField(blank=True, null=True,help_text='YYYY-MM-DD')
    phone = models.CharField(max_length=10)
    user = models.OneToOneField(User,on_delete=models.CASCADE)

    def __str__(self):
        return "profile of {}".format(self.user)



@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

class Category(models.Model):
    name = models.CharField(max_length=200,db_index=True)
    slug = models.SlugField(max_length=200,db_index=True,unique=True)
    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category,on_delete=models.SET('None'), related_name='products')
    name = models.CharField(max_length=200,db_index=True)
    slug = models.SlugField(max_length=200,db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d',blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created','name'] #('name','-created',)
        index_together = (('id','slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail',args=[self.id, self.slug])

class Slide(models.Model):
    image_name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=200,db_index=True)
    image = models.ImageField(upload_to='slider/%Y/%m/%d',blank=False)
    description = models.TextField(blank=True,null=True)
    slide = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)

shop/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import *
from dobwidget import DateOfBirthWidget

class SignUpForm(UserCreationForm):
    CLG_CHOICES = (
        ('MIT', 'Mahakal Institute Of Technology'),
        ('MITM', 'Mahakal Institute Of Technology And Management'),
    )
    BRANCH_CHOICES = (
        ('CS', 'Computer Science And Engineering'),
        ('IT', 'Information Technology'),
        ('CE', 'Civil Engineering'),
        ('ME', 'Mechanical Engineering'),
        ('EC', 'Electronic Engineering'),
    )
    college = forms.ChoiceField(choices=CLG_CHOICES)
    branch = forms.ChoiceField(choices=BRANCH_CHOICES)
    birth_date = forms.DateField()
    phone = forms.CharField(max_length=10)
    username = forms.CharField(label='Roll Number', max_length=12)
    class Meta:
        model = User
        fields = ('college','branch','username','email','birth_date','phone','password1', 'password2', )


    def clean_email(self):
        email = self.cleaned_data.get('email')
        username = self.cleaned_data.get('username')
        if email and User.objects.filter(email=email).exclude(username=username).exists():
            raise forms.ValidationError(u'Email addresses must be unique.')
        return email


#login form
class LoginForm(forms.Form):
    username = forms.CharField(max_length=12,label='Roll Number')
    password = forms.CharField(widget=forms.PasswordInput)

class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('college','branch','birth_date',)

shop/views.py
from django.shortcuts import render,redirect,HttpResponse,get_object_or_404
from .forms import *
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q

def index(request):
    categories = Category.objects.all()
    slider = Slide.objects.filter(slide=True)
    products = Product.objects.all()
    context = {
        'categories': categories,
        'slider': slider,
        'products':products
    }
    return render(request,'shop/index.html',context)

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            if len(username) == 12:
                a = username[:4]+username[6:]
                code = username[4] + username[5]
                branch = ["CS", "IT", "ME", "CE", "EC"]
                if code in branch and int(a):
                    pre = ['0714','0704']
                    b= username[:4]
                    if b in pre:
                        user = form.save()
                        user.refresh_from_db()  # load the profile instance created by the signal
                        user.profile.birth_date = form.cleaned_data.get('birth_date')
                        user.profile.college = form.cleaned_data.get('college')
                        user.profile.branch = form.cleaned_data.get('branch')
                        user.profile.phone = form.cleaned_data.get('phone')
                        user.save()
                        raw_password = form.cleaned_data.get('password1')
                        user = authenticate(username=user.username, password=raw_password)
                        login(request, user)
                        messages.success(request, 'Sign Up Successfull')
                        return redirect('shop:index')
                    else:
                        messages.error(request, 'Please enter correct Roll Number')
                else:
                    messages.error(request, 'Please enter correct Roll Number')
            else:
                messages.error(request, 'Please enter correct Roll Number')
    else:
        form = SignUpForm()
    return render(request, 'registration/signup.html', {'form': form})

def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['username'],password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('shop:dashboard')
                else:
                    messages.error(request,'Disabled account')
            else:
                messages.error(request,'Invalid login')
    else:
        form = LoginForm()
    return render(request, 'registration/login.html', {'form': form})

def logout_view(request):
    logout(request)
    return HttpResponse('logout successful')

def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return redirect('shop:index')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'registration/password_change.html', {'form': form})

@login_required
def edit(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user,data=request.POST)
        profile_form = ProfileEditForm(instance=request.user.profile,data=request.POST,files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Profile updated successfully')
        else:
            messages.error(request, 'Error updating your profile')
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)

    return render(request,'registration/profile_edit.html',{'user_form': user_form,'profile_form': profile_form})

@login_required
def dashboard(request):return render(request,'shop/dashboard.html',{'section': 'dashboard'})


#product list and detail
def product_list(request, category_slug=None):
    print(request.GET)
    query = request.GET.get('q')
    print(query)
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)

    if query is not None:
        products = products.filter(
            Q(name__icontains=query) |
            Q(slug__icontains=query) |
            #Q(category__icontains=query) |
            Q(description__icontains=query),
        )
    if category_slug:
        category = get_object_or_404(Category,slug=category_slug)
        #category = Category.objects.get(slug=category_slug)
        products = Product.objects.filter(category=category)
    return render(request,'shop/products/product_list.html',{'category':category,'categories':categories,'products':products})

def product_detail(request,id,slug):
    product = get_object_or_404(Product,id=id,slug=slug,available=True)
    return render(request,'shop/products/product_detail.html',{'product': product})

def allproducts(request):
    categories = Category.objects.all()
    products = Product.objects.all()
    return render(request,'shop/products/allproducts.html',{'categories':categories,'products':products})

shop/templates/shop/products/allproducts.html
{% extends 'base.html' %}
{% load shop_tags %}
{% load staticfiles %}
{% block title %}All Products{% endblock %}

{% block content %}
<h2 class="text-center">there are total {% total_posts %} products available</h2>

<ul>
    <h1 style="text-align:center;"><a href="#" data-toggle="tooltip" title="Click To Show / Hide All Product List">
        <button type="button"  data-toggle="collapse" data-target=".demo">All Products</button></a></h1>
    {% for c in categories %}
    <button type="button"  data-toggle="collapse" data-target="#{{ c.id }}">
        <li>
            <small><span class="glyphicon glyphicon-stop" aria-hidden="true"></span></small>
            {{ c.name }}
        </li>
        <div id="{{ c.id }}" class="collapse in demo">
            <ul class="list-group">
                {% for product in products %}
                <!--<li class="list-group-item">{{ product.name }}<span class="badge">{{ product.price }}</span></li>-->
                {% if product.category == c %}
                <li class="list-group-item">{{ product.name }}<span class="badge">{{ product.price }}</span></li>
                {% endif %}
                {% endfor %}
            </ul>
        </div>
        {% endfor %}
    </Button>
</ul>


{% endblock %}

shop/templates/shop/products/latest_product.html
{% load staticfiles %}
<ul class="nav">
{% for product in latest_product %}
 <li>
  <a href="{{ product.get_absolute_url }}" style="font-size:16px;color:black">
      <img style="height:40px;width:40px;" src="
      {% if product.image %}
        {{ product.image.url }}
      {% else %}
        {% static 'img/no_image.png' %}
      {% endif %}"/>
       {{ product.name }}
  </a>
 </li>
{% endfor %}
</ul>

shop/templates/shop/products/product_detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    {% if category %}{{ category.title }}{% else %}Products{% endif %}
{% endblock %}

{% block content %}
<h1>Category: <a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h1>
    <center>
        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}">
    </center>

    <center class="product-detail">

        <h1>{{ product.name }}</h1>

        <h3 class="price">Rs. {{ product.price }}</h3>
        {{ product.description|linebreaks }}
    </center>
{% endblock %}
{% block footer %}

{% endblock footer %}

shop/templates/shop/products/product_list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
    {% if category %}{{ category.name }}
    {% else %}
        Products
    {% endif %}
{% endblock %}



{% block content %}

<div class="">
    <h1>
        {% if category %}
            {{ category.name|upper }}
        {% else %}
            PRODUCTS
        {% endif %}
    </h1>
</div>
<div class="row">

    {% for product in products %}
    <div class="col-md-3">
        <div class="thumbnail">
        <a href="{{ product.get_absolute_url }}">
            <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" alt="Nature" style="width:100%;height:172px;">
            <div class="caption">
                <center>
                    <h3>{{ product.name }}</h3><br>
                    <h4>Rs. {{ product.price }}</h4>
                </center>

            </div>
        </div>
    </div>
     {% endfor %}
</div>
{% endblock content %}

shop/templates/shop/products/search.html
<form class="navbar-form" role="search" method="get" action="{% url 'shop:product_list' %}">
    <div class="input-group add-on">
      <input required class="form-control" placeholder="Search" name="q" id="srch-term" type="text">
      <div class="input-group-btn">
        <button class="btn btn-default" type="submit">GO</button>
      </div>
    </div>
  </form>