canteen/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

#password reset
    re_path(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    re_path(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',auth_views.password_reset_confirm, name='password_reset_confirm'),
    re_path(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),


    path('',include('shop.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path,re_path
from . import views
from django.contrib.auth.views import  (login,logout,password_reset,password_reset_done,password_reset_confirm,)
from django.contrib.auth import views as auth_views
#from .feeds import LatestProductFeed

app_name = 'shop'
urlpatterns = [
    path('',views.index,name='index'),
    path('signup/',views.signup,name='signup'),
    path('login/',views.user_login,  name='login'),
    path('logout/',auth_views.logout,name='logout'),
    #path('feed/',LatestProductFeed(),name='product_feed'),
    re_path(r'^password-change/$', views.change_password, name='change_password'),

    re_path('profile/edit/', views.edit, name='edit'),
    path('', views.dashboard, name='dashboard'),

#products
    re_path(r'^product_list/$', views.product_list, name='product_list'),
    re_path(r'^(?P<category_slug>[-\w]+)/$',views.product_list,name='product_list_by_category'),
    re_path(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',views.product_detail,name='product_detail'),
    path('all/products/',views.allproducts,name='allproducts'),

]

shop/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse

# Create your models here.
class Profile(models.Model):
    CLG_CHOICES = (
        ('MIT', 'Mahakal Institute Of Technology'),
        ('MITM', 'Mahakal Institute Of Technology And Management'),
    )
    BRANCH_CHOICES = (
        ('CS', 'Computer Science And Engineering'),
        ('IT', 'Information Technology'),
        ('CE', 'Civil Engineering'),
        ('ME', 'Mechanical Engineering'),
        ('EC', 'Electronic Engineering'),
    )
    college = models.CharField(max_length=5,choices=CLG_CHOICES)
    branch = models.CharField(max_length=5,choices=BRANCH_CHOICES)
    birth_date = models.DateField(blank=True, null=True,help_text='YYYY-MM-DD')
    phone = models.CharField(max_length=10)
    user = models.OneToOneField(User,on_delete=models.CASCADE)

    def __str__(self):
        return "profile of {}".format(self.user)



@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

class Category(models.Model):
    name = models.CharField(max_length=200,db_index=True)
    slug = models.SlugField(max_length=200,db_index=True,unique=True)
    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category,on_delete=models.SET('None'), related_name='products')
    name = models.CharField(max_length=200,db_index=True)
    slug = models.SlugField(max_length=200,db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d',blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created','name'] #('name','-created',)
        index_together = (('id','slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail',args=[self.id, self.slug])

class Slide(models.Model):
    image_name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=200,db_index=True)
    image = models.ImageField(upload_to='slider/%Y/%m/%d',blank=False)
    description = models.TextField(blank=True,null=True)
    slide = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)

shop/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import *
from dobwidget import DateOfBirthWidget

class SignUpForm(UserCreationForm):
    CLG_CHOICES = (
        ('MIT', 'Mahakal Institute Of Technology'),
        ('MITM', 'Mahakal Institute Of Technology And Management'),
    )
    BRANCH_CHOICES = (
        ('CS', 'Computer Science And Engineering'),
        ('IT', 'Information Technology'),
        ('CE', 'Civil Engineering'),
        ('ME', 'Mechanical Engineering'),
        ('EC', 'Electronic Engineering'),
    )
    college = forms.ChoiceField(choices=CLG_CHOICES)
    branch = forms.ChoiceField(choices=BRANCH_CHOICES)
    birth_date = forms.DateField()
    phone = forms.CharField(max_length=10)
    username = forms.CharField(label='Roll Number', max_length=12)
    class Meta:
        model = User
        fields = ('college','branch','username','email','birth_date','phone','password1', 'password2', )


    def clean_email(self):
        email = self.cleaned_data.get('email')
        username = self.cleaned_data.get('username')
        if email and User.objects.filter(email=email).exclude(username=username).exists():
            raise forms.ValidationError(u'Email addresses must be unique.')
        return email


#login form
class LoginForm(forms.Form):
    username = forms.CharField(max_length=12,label='Roll Number')
    password = forms.CharField(widget=forms.PasswordInput)

class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('college','branch','birth_date',)

shop/views.py
from django.shortcuts import render,redirect,HttpResponse,get_object_or_404
from .forms import *
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q

def index(request):
    categories = Category.objects.all()
    slider = Slide.objects.filter(slide=True)
    products = Product.objects.all()
    context = {
        'categories': categories,
        'slider': slider,
        'products':products
    }
    return render(request,'shop/index.html',context)

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            if len(username) == 12:
                a = username[:4]+username[6:]
                code = username[4] + username[5]
                branch = ["CS", "IT", "ME", "CE", "EC"]
                if code in branch and int(a):
                    pre = ['0714','0704']
                    b= username[:4]
                    if b in pre:
                        user = form.save()
                        user.refresh_from_db()  # load the profile instance created by the signal
                        user.profile.birth_date = form.cleaned_data.get('birth_date')
                        user.profile.college = form.cleaned_data.get('college')
                        user.profile.branch = form.cleaned_data.get('branch')
                        user.profile.phone = form.cleaned_data.get('phone')
                        user.save()
                        raw_password = form.cleaned_data.get('password1')
                        user = authenticate(username=user.username, password=raw_password)
                        login(request, user)
                        messages.success(request, 'Sign Up Successfull')
                        return redirect('shop:index')
                    else:
                        messages.error(request, 'Please enter correct Roll Number')
                else:
                    messages.error(request, 'Please enter correct Roll Number')
            else:
                messages.error(request, 'Please enter correct Roll Number')
    else:
        form = SignUpForm()
    return render(request, 'registration/signup.html', {'form': form})

def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['username'],password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('shop:dashboard')
                else:
                    messages.error(request,'Disabled account')
            else:
                messages.error(request,'Invalid login')
    else:
        form = LoginForm()
    return render(request, 'registration/login.html', {'form': form})

def logout_view(request):
    logout(request)
    return HttpResponse('logout successful')

def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return redirect('shop:index')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'registration/password_change.html', {'form': form})

@login_required
def edit(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user,data=request.POST)
        profile_form = ProfileEditForm(instance=request.user.profile,data=request.POST,files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Profile updated successfully')
        else:
            messages.error(request, 'Error updating your profile')
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)

    return render(request,'registration/profile_edit.html',{'user_form': user_form,'profile_form': profile_form})

@login_required
def dashboard(request):return render(request,'shop/dashboard.html',{'section': 'dashboard'})


#product list and detail
def product_list(request, category_slug=None):
    print(request.GET)
    query = request.GET.get('q')
    print(query)
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)

    if query is not None:
        products = products.filter(
            Q(name__icontains=query) |
            Q(slug__icontains=query) |
            #Q(category__icontains=query) |
            Q(description__icontains=query),
        )
    if category_slug:
        category = get_object_or_404(Category,slug=category_slug)
        #category = Category.objects.get(slug=category_slug)
        products = Product.objects.filter(category=category)
    return render(request,'shop/products/product_list.html',{'category':category,'categories':categories,'products':products})

def product_detail(request,id,slug):
    product = get_object_or_404(Product,id=id,slug=slug,available=True)
    return render(request,'shop/products/product_detail.html',{'product': product})

def allproducts(request):
    categories = Category.objects.all()
    products = Product.objects.all()
    return render(request,'shop/products/allproducts.html',{'categories':categories,'products':products})

shop/templates/base.html
{% load staticfiles %}
{% load shop_tags %}
<body>
<head>
    <title>{% block title %}{% endblock %}</title>
    {% block head %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
    <link rel="stylesheet" href="{% static 'font-awesome/css/font-awesome.css' %}"/>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% endblock %}
</head>
<body style="background:#EBEBEB">


<div class="container-fluid marque">
    <div class="row">
        <div class="col-md-12 ">
            <marquee  class="" behavior="scroll" direction="left">Developed By Pankaj Malviya And Gaurav Arora</marquee>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="container">
        <div class="row">
            <div class="col-md-12 ">
                <h1 class="heading" >Baba Mahakal</b></h1>
                <p class="slogen">Feel The Test</p>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid navigation" >
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <nav class="primary-navigation " id="navigation1">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                                <span class="glyphicon glyphicon-tasks" style="color:white"></span>
                            </button>
                            <h6 style="color:white" class="navbar-brand hidden-md hidden-lg">Menu</h6>
                        </div>
                        <div class="collapse navbar-collapse" id="myNavbar">
                            <ul class="nav navbar-nav">
                                <li class="active"><a href="{% url 'shop:index' %}">Home</a></li>
                                {% for c in categories %}
                                <li {% if category.slug == c.slug %}class="selected active"{% endif %}>
                                <a href="{{ c.get_absolute_url }}" >{{ c.name }}</a>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                </nav>
            </div>
        </div>
    </div>
</div>
<div class="conatiner-fluid">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                {% if request.user.is_authenticated %}
                <ul class="nav navbar-nav">
                    <li {% if section == "dashboard" %}class="selected"{% endif %}>
                        <a href="{% url 'shop:dashboard' %}">My dashboard</a>
                    </li>
                    <li {% if section == "Edit Profile" %}class="selected"{% endif %}>
                        <a href="{% url 'shop:edit' %}">Edit profile</a>
                    </li>
                    <li {% if section == "change_password" %}class="selected"{% endif %}>
                        <a href="{% url 'shop:change_password' %}">Change password</a>
                    </li>
                </ul>
                {% endif %}
                <div class="pull-right">
                {% if request.user.is_authenticated %}
                    Hello {{ request.user.first_name }},<a href="{% url 'shop:logout' %}">Logout</a>

                {% else %}
                    <ul class="nav navbar-right navbar-nav">
                        <li><a href="{% url 'shop:login' %}"><span class="glyphicon glyphicon-log-in"></span> Log-in  </a></li>
                        <li><a href="{% url 'shop:signup' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
                    </ul>


                {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid" style="margin-top:30px">
    <div class="container">
        <div class="row">
            <div class="col-md-9 ">
                {% block content %}
                <div id="myCarousel" class="carousel slide" data-ride="carousel" style="">
                    <!-- Indicators -->
                    <ol class="carousel-indicators">
                        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                        <li data-target="#myCarousel" data-slide-to="1"></li>
                        <li data-target="#myCarousel" data-slide-to="2"></li>
                    </ol>
                    <!-- Wrapper for slides -->
                    <center class="carousel-inner slider" >
                        <div class="item active">
                            <img class="img-responsive" src="{% static 'img/jai-mahakal.jpg' %}" alt="mahakal">
                        </div>
                        {% for slide in slider %}
                        <div class="item">
                            <img class="img-responsive" src="{{ slide.image.url }}" alt="{{ slide.name }}"">
                        </div>
                        {% endfor %}
                    </center>
                    <!-- Left and right controls -->
                    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                        <span class="glyphicon glyphicon-chevron-left"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="right carousel-control" href="#myCarousel" data-slide="next">
                        <span class="glyphicon glyphicon-chevron-right"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
                {% endblock content %}
            </div>
            <div class="col-md-3">
                {% block sidebar %}

                <!-- search bar -->
                {% include 'shop/products/search.html' %}
                <!-- end of search bar-->

                <!-- latest product -->
                <div>
                    <center><h2>Latest Products</h2></center>
                    {% latest_product %}
                </div><!-- end latest product-->

                {% endblock sidebar %}
            </div>
        </div>
    </div>
</div>

<!--footer start -->
{% block footer %}
<section id="footer" >
        <div class="container">
            <div class="row">
                <center class="col-md-4" >
                        <h3>CONTACT <span>INFO</span></h3>
                        <div class="info">
                            <ul>
                                <li>
                                  <h4><i class="fa fa-phone"></i> Telefone</h4>
                                  <p>0734 - 1234567</p>
                                </li>
                                <li>
                                  <h4><i class="fa fa-map-marker"></i> Address</h4>
                                  <p>Mit Ujjain</p>
                                </li>
                                <li>
                                  <h4><i class="fa fa-envelope"></i> E-mail</h4>
                                  <p>canteen@gmail.com</p>

                                </li>
                            </ul>
                        </div>
                </center>

                <!-- .col-md-4 close -->
                <center class="col-md-4">
                        <h3>LATEST <span >BLOG POSTS</span></h3>
                        <div class="blog">
                            <ul>
                                <li>
                                    <h4><a href="#">Nov 9-2014</a></h4>
                                    <p>Lorem ipsum dolor sit amet, consectetur adip iscing elit. Curabitur ut blandit sapien</p>
                                </li>
                                <li>
                                    <h4><a href="#">Sep 8-2014</a></h4>
                                    <p>Lorem ipsum dolor sit amet, consectetur adip iscing elit. Curabitur ut blandit sapien</p>
                                </li>
                            </ul>
                        </div>

                </center>
                <!-- .col-md-4 close -->
                <center class="col-md-4">
                        <div class="social-media-link">
                            <h3>Follow <span >US</span></h3>
                            <ul>
                                <li>
                                    <a href="#"><i class="fa fa-twitter"></i></a>
                                </li>
                                <li>
                                    <a href="#"><i class="fa fa-facebook"></i></a>
                                </li>
                                <li>
                                    <a href="#"><i class="fa fa-dribbble"></i></a>
                                </li>
                                <li>
                                    <a href="#"><i class="fa fa-behance"></i></a>
                                </li>
                            </ul>
                        </div>
                </center>
                <!-- .col-md-4 close -->
            </div><!-- .row close -->
        </div><!-- .containe close -->
    </section><!-- #footer close -->
{% endblock footer %}
<!-- footer  bottom start -->

<footer id="footer-bottom">
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-sm-12">
                    <div class="block">
                        <p>Copyright &copy; 2018 - All Rights Reserved. Design and Developed By <a href="#">Pankaj Malviya</a>
                        And <a href="#">Gaurav Arora</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </footer>

</body>
</html>